### ISSUE TITLE
[BUG] live-time match information not linked

### ISSUE THREAD

**Issue by parkyabal** [RCVolus/valorant-observer-tool#1]
live-time match information not linked 

2022-07-19T02:41:42.063Z [warn ] module-teams: matches could not be loaded

**Comment by parkyabal** [comment]
<html>
<body>


valo-match-info | Not Live | Unknown | Unknown | Unknown
-- | -- | -- | -- | --
valo-pre-game | Not Live | Unknown | Unknown | Unknown
valo-in-game | Unknown | Unknown | Unknown | Unknown
valo-post-game | Not Live | Unknown | Unknown | Unknown


</body>
</html>

**Comment by Himyu** [comment]
the first issue you posted is not really a bug it just tells you that there are no games in the database and therefore can not be loaded.
And all Valorant modules are still in development and especially the in-game stuff is not working atm

**Comment by Himyu** [comment]
These problems are not related to the observer tool itself so i will close this issue here. if you still need help please add an issue over at https://github.com/RCVolus/league-prod-toolkit
