### ISSUE TITLE
[BUG] Observer tool fails to fetch matchid

### ISSUE THREAD

**Issue by sod101316** [RCVolus/valorant-observer-tool#2]
![unknown](https://user-images.githubusercontent.com/59684822/180018231-4149f319-5161-401d-a6d8-e4ca8852eb80.png)

**Comment by Himyu** [comment]
Could you please provide more details about how you used the tool and when or how you encountered this error.

**Comment by sod101316** [comment]
I used it on the Korean server, and in a custom room, a friend joined the blue team and I entered the spectator.

**Comment by cedrickalegroso** [comment]
Hi just got the same error, I'm from SEA so I just picked the nearest server in the League tool kit (tried JP1 and KR) then successfully hooked the app with server and valorant, but when I start a game as an observer (just me and a friend for testing) I also got "fails to fetch matchid".

**Comment by cedrickalegroso** [comment]
btw, I'm using this observer tool and the league tool kit with a development API key from riot. Maybe that could be a reason? restricted API access? just checked on the Riot API docs and saw that Valorant Match API requires some elevated API access.

**Comment by Himyu** [comment]
We are aware of this. Arm it seems like it's only working in Europe. We are trying to fix this issue, as fast as we can

**Comment by Himyu** [comment]
This should be fixed with the newest update of the tool [v1.1.0](https://github.com/RCVolus/valorant-observer-tool/releases/tag/v1.1.0).
You can install the update by simply opening your tool and letting it auto-update or download it from the release page.

Please try it out and give us some feedback :)

**Comment by sod101316** [comment]
> 
Thanks for your update. I tried the new version, it gave no error on the Korean server. But prod-tool gave an error and 'Valorant PreGame & Loading' page didn't work
![image](https://user-images.githubusercontent.com/59684822/183310927-c8b5d592-2604-4965-83c5-baf2d90ef5d9.png)

**Comment by Himyu** [comment]
ok i will have a look at that

**Comment by sod101316** [comment]
thank you i look forward to your reply

**Comment by Himyu** [comment]
Can you please provide me with a screenshot of the module page in the browser, so I can see with modules you have installed?

**Comment by sod101316** [comment]
![image](https://user-images.githubusercontent.com/59684822/183640119-a05b7828-f774-4425-9a9c-2b8d19f28247.png)

**Comment by Himyu** [comment]
I am closing this issue and tracking it in the new one. Since this problem has nothing to do with the original problem and also is not related to the observer tool.
