### ISSUE TITLE
Question: does this send ingame information

### ISSUE THREAD

**Issue by Manokii** [RCVolus/valorant-observer-tool#4]
Just a quick question, does this tool exposes ingame information such as current round, round results, kda and everything that happens in a match?

I wanted to build a custom UI for broadcast, similar to the lol-prod-kit

**Comment by stXwinter** [comment]
Have you managed to get the valorant observer tool connecting? I cant seem to get mine connecting

**Comment by Himyu** [comment]
no there is no such thing for in-game atm. It only exposes data for post-game stats and for the agent select. if there was our prod tool would probably include stuff like this.

**Comment by Manokii** [comment]
Thank you for answering my question! I'm gonna close this now

> no there is no such thing for in-game atm. It only exposes data for post-game stats and for the agent select. if there was our prod tool would probably include stuff like this. For agent select the prod tool already has a module and for post-game we are currently working on finalizing the modules for that aswell
