### ISSUE TITLE
Question Valorant Match

### ISSUE THREAD

**Issue by EidechseBorke8** [RCVolus/valorant-observer-tool#5]
Hello,
unfortunately, the Game State page does not work properly for me or I do not know if I am doing something wrong.
Here is the procedure I use.
1. i start the League Production Toolkit.
2. i start the Valorant Observer Tool. 
3. i start Valorant and go into a custom match as a spectator.
4. i connect to the Valorant Obsever Tool (i am connected).
5. no game is displayed in the League Production Tool. 

Am I doing something wrong?

Best regards,
Jan

**Comment by Himyu** [comment]
Do still have any problems or can I close this issue?
