### ISSUE TITLE
[BUG] Not Connected To Server

### ISSUE THREAD

**Issue by i6h** [RCVolus/valorant-observer-tool#9]
**Describe the bug**
Connect ECONNREFUSED 127.0.0.1:3006

**Screenshots**
![image](https://user-images.githubusercontent.com/50395633/219635462-675b72a9-9d02-47b0-9d38-048772eb3637.png)

**System:**
 - OS: win10

**Comment by baigojahanzaib** [comment]
i get this also

**Comment by Himyu** [comment]
Please make sure the prod tool is running as well and your configuration for the IP and port a correct

**Comment by hadeszj** [comment]
> Please make sure the prod tool is running as well and your configuration for the IP and port a correct

i have the same issue, can u please give us more details on how to do that please

**Comment by i6h** [comment]
> Please make sure the prod tool is running as well and your configuration for the IP and port a correct

all good but still not working same error

**Comment by sdomi4** [comment]
Could you post the resolution to your issue to help out other people encountering the same thing?

**Comment by hadeszj** [comment]
i can make it green and connected
but nothing  is showing in the software

**Comment by MrFoxyOfficial** [comment]
> all good fixed!

Any tips on how you resolved it?
